# === Nexus
nexus_docker_image: sonatype/nexus3:3.56.0
nexus_autoconfiguration: true


# === Nginx
nexus_nginx_docker_image: nginx:latest
nexus_backend_name: nexus
nexus_backend_port: 8081
nexus_server_name: nexus.example.org
# Example: nexus_server_alias: repo.example.org
nexus_server_alias: 


# == Let's Encrypt
nexus_certbot_email: admin@example.org
nexus_certbot_renew_cron_hour: 3
nexus_certbot_renew_cron_minute: 20
nexus_certbot_staging: true


# === Docker Compose
docker_compose_version: v2.9.0
